export const queryKeys = {
  profile: ['profile'] as const,
  roles: ['roles'] as const,
  departments: ['departments'] as const,
  designations: ['designations'] as const,
  employees: ['employees'] as const,
  employee: (id: string) => ['employees', id] as const,
  employeeStats: ['employees', 'stats'] as const,
  attendance: ['attendance'] as const,
  attendanceMonth: (employeeId: string, month: string) => ['attendance', employeeId, month] as const,
  todayAttendance: (employeeId?: string) => ['attendance', 'today', employeeId] as const,
  leaveTypes: ['leaveTypes'] as const,
  leaveRequests: ['leaveRequests'] as const,
  leaveBalances: (employeeId: string, year: number) => ['leaveBalances', employeeId, year] as const,
  payroll: ['payroll'] as const,
  payrollPeriod: (period: string) => ['payroll', period] as const,
  payrollProfiles: ['payrollProfiles'] as const,
  documents: ['documents'] as const,
  documentsFor: (employeeId: string) => ['documents', employeeId] as const,
  tasks: ['tasks'] as const,
  announcements: ['announcements'] as const,
  holidays: ['holidays'] as const,
  performanceGoals: ['performanceGoals'] as const,
  performanceReviews: ['performanceReviews'] as const,
  jobOpenings: ['jobOpenings'] as const,
  candidates: ['candidates'] as const,
  interviews: ['interviews'] as const,
  interviewSlots: ['interviewSlots'] as const,
  offers: ['offers'] as const,
  notifications: ['notifications'] as const,
  auditLogs: ['auditLogs'] as const,
  dashboardStats: ['dashboardStats'] as const,
}
